version: "3.9"

services:
  spring_hexagonal:
    container_name: spring_hexagonal
    image: spring_hexagonal
    build:
      context: ./boot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/PERSONS
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PERSONS
